/**
 * 便民车监管平台
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
 * @property `type` 告警类型【0:偏航, 1:逆行, 2:违停, 3:超速】
 * @property `location` 火星坐标
 * @property `speed` 速度
 * @property `direction` 方位角
 * @property `alarmTime` 告警时的坐标定位时间
 * @property `carNo` 车牌号码
 * @property `companyName` 公司名称
 */
export interface AlarmsIdBody {
  /**
   * 告警类型【0:偏航, 1:逆行, 2:违停, 3:超速】
   */
  type: number
  /**
   * 火星坐标
   */
  location: string
  /**
   * 速度
   */
  speed: number
  /**
   * 方位角
   */
  direction: number
  /**
   * 告警时的坐标定位时间
   */
  alarmTime: string
  /**
   * 车牌号码
   */
  carNo: string
  /**
   * 公司名称
   */
  companyName: string
}
