/**
 * 便民车监管平台
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
 * @property `companyName` 单位名称
 * @property `carNo` 车牌号码
 * @property `beginDate` 起始日期
 * @property `endDate` 结束日期
 * @property `phQuantity` 偏航告警数量
 * @property `nxQuantity` 逆行告警数量
 * @property `wtQuantity` 违停告警数量
 * @property `csQuantity` 超速告警数量
 */
export interface AlarmsStatisticsBodyRecords {
  /**
   * 单位名称
   */
  companyName: string
  /**
   * 车牌号码
   */
  carNo: string
  /**
   * 起始日期
   */
  beginDate: string
  /**
   * 结束日期
   */
  endDate: string
  /**
   * 偏航告警数量
   */
  phQuantity: number
  /**
   * 逆行告警数量
   */
  nxQuantity: number
  /**
   * 违停告警数量
   */
  wtQuantity: number
  /**
   * 超速告警数量
   */
  csQuantity: number
}
