/**
 * 便民车监管平台
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
 * @property `[now]`
 * @property `[statusCode]`
 * @property `body` 未读告警数量
 */
export interface AlarmReadId {
  now?: string
  statusCode?: number
  /**
   * 未读告警数量
   */
  body: number
}
