/**
 * 便民车监管平台
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
 * @property `alarmTime` 告警时间
 * @property `alarmType` 告警类型【0:偏航, 1:逆行, 2:违停, 3:超速】
 * @property `quantity` 告警数量
 */
export interface AlarmsCollectBody {
  /**
   * 告警时间
   */
  alarmTime: string
  /**
   * 告警类型【0:偏航, 1:逆行, 2:违停, 3:超速】
   */
  alarmType: string
  /**
   * 告警数量
   */
  quantity: number
}
