/**
 * 便民车监管平台
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
 * @property `alarmType` 告警类型
 * @property `quantity` 告警次数
 */
export interface AlarmsStatisticsAlarmQuantities {
  /**
   * 告警类型
   */
  alarmType: number
  /**
   * 告警次数
   */
  quantity: number
}
