/**
 * 便民车监管平台
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
 * @property `alertTime` 告警时间
 * @property `alertTypeId` 告警类型ID
 * @property `quantity` 告警数量
 */
export interface AlertsBody {
  /**
   * 告警时间
   */
  alertTime: string
  /**
   * 告警类型ID
   */
  alertTypeId: string
  /**
   * 告警数量
   */
  quantity: number
}
