/**
 * 便民车监管平台
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
 * @property `companyName` 单位名称
 * @property `quantity` 数量
 */
export interface CarDistributionBody {
  /**
   * 单位名称
   */
  companyName: string
  /**
   * 数量
   */
  quantity: number
}
