/**
 * 便民车监管平台
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
 * @property `id` 车辆ID
 * @property `carNo` 车牌号码
 * @property `companyName` 公司名称
 * @property `runState` 行驶状态
 * @property `[point]`
 */
export interface CarIdBody {
  /**
   * 车辆ID
   */
  id: string
  /**
   * 车牌号码
   */
  carNo: string
  /**
   * 公司名称
   */
  companyName: string
  /**
   * 行驶状态
   */
  runState: string
  point?: models.CarIdBodyPoint
}
