/**
 * 便民车监管平台
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
 * @description 当前位置
 * @property `alarmType` 告警类型
 * @property `location` 火星坐标(格式: 113.448, 23.1574)
 * @property `speed` 速度
 * @property `direction` 方位角
 * @property `locateTime` 定位时间
 * @property `runState` 车辆状态[1:行驶, 2:停驶, 3:异常]
 */
export interface CarIdBodyLocation {
  /**
   * 告警类型
   */
  alarmType: number
  /**
   * 火星坐标(格式: 113.448, 23.1574)
   */
  location: string
  /**
   * 速度
   */
  speed: string
  /**
   * 方位角
   */
  direction: string
  /**
   * 定位时间
   */
  locateTime: number
  /**
   * 车辆状态[1:行驶, 2:停驶, 3:异常]
   */
  runState: number
}
