/**
 * 便民车监管平台
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
 * @property `id` 车辆ID
 * @property `carNo` 车牌号码
 * @property `terminalNo` 终端bian hao
 * @property `companyId` 公司ID
 * @property `companyName` 公司名称
 * @property `name` 车辆名称
 * @property `typeId` 类型ID
 * @property `typeName` 类型名称
 * @property `model` 幸好
 * @property `[location]`
 */
export interface CarIdBody {
  /**
   * 车辆ID
   */
  id: string
  /**
   * 车牌号码
   */
  carNo: string
  /**
   * 终端bian hao
   */
  terminalNo: string
  /**
   * 公司ID
   */
  companyId: string
  /**
   * 公司名称
   */
  companyName: string
  /**
   * 车辆名称
   */
  name: string
  /**
   * 类型ID
   */
  typeId: string
  /**
   * 类型名称
   */
  typeName: string
  /**
   * 幸好
   */
  model: string
  location?: models.CarIdBodyLocation
}
