/**
 * 便民车监管平台
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
 * @property `carId` 车辆ID
 * @property `beginTime` 开始时间
 * @property `endTime` 结束时间
 */
export interface CarLocationsBody {
  /**
   * 车辆ID
   */
  carId: string
  /**
   * 开始时间
   */
  beginTime: string
  /**
   * 结束时间
   */
  endTime: string
}
