/**
 * 便民车监管平台
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
 * @property `id` 车辆ID
 * @property `terminalNo` 终端编号
 * @property `carNo` 车牌号码
 * @property `runState` 车辆状态[1:行驶, 2:停驶, 3:警告]
 * @property `alarmType` 告警类型 基础类型为【0:无告警, 1:偏航, 2逆行, 4:违停, 8:超速】 多种告警则数值累加，如3为偏航+逆行
 * @property `location` 火星坐标(格式: 113.339, 23.1874)
 * @property `speed` 速度
 * @property `direction` 方位角
 * @property `locateTime` 定位时间
 */
export interface CarLocationBody {
  /**
   * 车辆ID
   */
  id: string
  /**
   * 终端编号
   */
  terminalNo: string
  /**
   * 车牌号码
   */
  carNo: string
  /**
   * 车辆状态[1:行驶, 2:停驶, 3:警告]
   */
  runState: number
  /**
   * 告警类型 基础类型为【0:无告警, 1:偏航, 2逆行, 4:违停, 8:超速】 多种告警则数值累加，如3为偏航+逆行
   */
  alarmType: string
  /**
   * 火星坐标(格式: 113.339, 23.1874)
   */
  location: string
  /**
   * 速度
   */
  speed: string
  /**
   * 方位角
   */
  direction: string
  /**
   * 定位时间
   */
  locateTime: string
}
