/**
 * 便民车监管平台
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
 * @property `id` 主键ID
 * @property `carNo` 车牌号码
 * @property `companyId` 公司ID
 * @property `companyName` 公司名称
 * @property `runState` 车辆状态[1:行驶, 2:停驶, 3:异常]
 */
export interface CarsBodyRecords {
  /**
   * 主键ID
   */
  id: string
  /**
   * 车牌号码
   */
  carNo: string
  /**
   * 公司ID
   */
  companyId: string
  /**
   * 公司名称
   */
  companyName: string
  /**
   * 车辆状态[1:行驶, 2:停驶, 3:异常]
   */
  runState: string
}
