/**
 * 便民车监管平台
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
 * @property `[companyId]` 单位ID
 * @property `[runState]` 行驶状态[1:行驶, 2:停驶, 3:异常]
 * @property `[carNo]` 车牌号码
 */
export interface CarsBody {
  /**
   * 单位ID
   */
  companyId?: string
  /**
   * 行驶状态[1:行驶, 2:停驶, 3:异常]
   */
  runState?: string
  /**
   * 车牌号码
   */
  carNo?: string
}
