/**
 * 便民车监管平台
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
 * @property `totalQuantity` 车辆总数量
 * @property `statistics` 统计信息
 */
export interface CarStateBody {
  /**
   * 车辆总数量
   */
  totalQuantity: number
  /**
   * 统计信息
   */
  statistics: Array<models.CarStateBodyStatistics>
}
