/**
 * 便民车监管平台
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
 * @property `runState` 车辆状态[1:行驶, 2:停驶, 3:异常]
 * @property `quantity` 数量
 */
export interface CarStateBodyStatistics {
  /**
   * 车辆状态[1:行驶, 2:停驶, 3:异常]
   */
  runState: string
  /**
   * 数量
   */
  quantity: string
}
