/**
 * 便民车监管平台
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
 * @property `totalQuantity` 车辆总数量
 * @property `runningQuantity` 行驶车辆数量
 * @property `stopQuantity` 停驶车辆数量
 * @property `abnormalQuantity` 警告车辆数量
 */
export interface CarStateBody {
  /**
   * 车辆总数量
   */
  totalQuantity: number
  /**
   * 行驶车辆数量
   */
  runningQuantity: number
  /**
   * 停驶车辆数量
   */
  stopQuantity: number
  /**
   * 警告车辆数量
   */
  abnormalQuantity: number
}
