/**
 * 便民车监管平台
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
 * @property `id` 主键ID
 * @property `name` 名称
 * @property `[address]` 地址
 * @property `[uscc]` 统一信用代码
 * @property `[contact]` 联系人
 * @property `[phone]` 联系电话
 */
export interface CompanyBody {
  /**
   * 主键ID
   */
  id: string
  /**
   * 名称
   */
  name: string
  /**
   * 地址
   */
  address?: string
  /**
   * 统一信用代码
   */
  uscc?: string
  /**
   * 联系人
   */
  contact?: string
  /**
   * 联系电话
   */
  phone?: string
}
