/**
 * 便民车监管平台
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
 * @property `[token]` 登录用的Token
 * @property `[refreshToken]` 刷新用的Token
 */
export interface RefreshBody {
  /**
   * 登录用的Token
   */
  token?: string
  /**
   * 刷新用的Token
   */
  refreshToken?: string
}
