/**
 * 便民车监管平台
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
 * @property `gid` 高德电子围栏gid
 * @property `carId` 车辆ID
 */
export interface SettingFenceCarsBody {
  /**
   * 高德电子围栏gid
   */
  gid: string
  /**
   * 车辆ID
   */
  carId: string
}
